[data]
seq_len = 720
pred_len = 96
label_len = 96
enc_in  = 2
[hyperparams]
lr = 0.0007
batch_size = 32
weight_decay = 0.0
[electric_data_module]
label_len = 32
scale = true
time_enc = false
batch_size =32
num_workers = 4
inverse = false
[model.clip]
d_model = 128
dropout = 0.7
patch_len = 8
past_channels = 40
channels = 38
future_channels = 2
embed_dim = 2
past_static_nums = [2,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96]
future_static_nums = [2,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96,8,96]
accum_freq = 1
inverse = false
scale = true
time_enc = false
is_past = false