[data]
seq_len = 720
pred_len = 96
label_len = 48
enc_in = 862
[hyperparams]
lr =  0.005
batch_size =24
weight_decay = 0.0
[electric_data_module]
label_len = 96
scale = true
time_enc = false
batch_size = 24
num_workers = 4
inverse = false
[model.clip]
patch_len= 48
past_channels = 862
channels = 0
future_channels = 862
embed_dim = 2
d_model = 512
dropout = 0.7
past_static_nums = [13,32,8,25]
future_static_nums = [13,32,8,25]
accum_freq = 1
inverse = false
scale = true
time_enc = false
is_past = false